name: Fetch Beartai Posts to Airtable

on:
  schedule:
    - cron: '* */12 * * *'
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn

      - name: Start Fetching
        env:
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
          AIRTABLE_WORKING_BASE: ${{ secrets.AIRTABLE_WORKING_BASE }}
          TZ: Asia/Bangkok
        run: yarn start
